### ISSUE TITLE
Can this be used for Teams

### ISSUE THREAD

**Issue by sarangvyas** [InterativaDigital/bitbucket-bulk-add-webhook#1]
I tried using the php file for bulk updating the webhooks for an user and it worked just fine. However, I want to bulk update the Teams repository webhooks. 
Is this possible?

I tried some modifications to bitbucket_bulk_add_webhook.php but it is not working. 

Thanks,
Sarang

**Comment by sarangvyas** [comment]
@felladrin @interativa Can you please answer the query posted above ?

**Comment by felladrin** [comment]
Hi, Sarang.

I don't know if it would work for a team, as it needs an account for using the API.

Couldn't you assign a user (the user you'll set up for this php script) to all repositories?

In our company, we use it under a single account, which holds all repos. And, from that account, we allowed all other company developers to access the account repositories.

**Comment by sarangvyas** [comment]
Thanks @felladrin for a quick reply. 
However in our company, we have Team created with multiple repositories in it. The team do have a teamid, email address but does not have a password to authenticate. There are multiple users who have admin rights, I am one of them.
There is bitbucket API for Teams and the URL for accessing Teams repositories is different than account. Whenever I run the script with my bitbucket username, it only lists repositories created by me or under my name and does not list the Team repositories. 

Can you check if this can run/modified for the team? I am novice to php and could not find better modules for bitbucket in python, which i know little bit.

**Comment by WillPresley** [comment]
[**@sarangvyas**](https://github.com/sarangvyas) commented on [Mar 7, 2016, 12:42 AM EST](https://github.com/InterativaDigital/bitbucket-bulk-add-webhook/issues/1#issuecomment-193113592):

> Thanks [@felladrin](https://github.com/felladrin) for a quick reply.   
> 
> However in our company, we have Team created with multiple repositories in it. The team do have a teamid, email address but does not have a password to authenticate. There are multiple users who have admin rights, I am one of them.  
> 
> There is bitbucket API for Teams and the URL for accessing Teams repositories is different than account. Whenever I run the script with my bitbucket username, it only lists repositories created by me or under my name and does not list the Team repositories. 
> 
> Can you check if this can run/modified for the team? I am novice to php and could not find better modules for bitbucket in python, which i know little bit.

Check out my fork here: https://github.com/WillPresley/bitbucket-bulk-add-webhook

I also replied to your comment in the older studio24 repository.

**Comment by felladrin** [comment]
> Can you check if this can run/modified for the team? I am novice to php and could not find better modules for bitbucket in python, which i know little bit.

I understand, @sarangvyas, but unfortunately I can't test it for teams.
I hope @WillPresley's fork can help you with that matter.
For now, this script will remain as is.
